import { Space_Grotesk } from "next/font/google";
import { I18nProvider } from "@/i18n/I18nContext";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "SwissMat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <body
        className={`${spaceGrotesk.variable} antialiased`}
      >
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
